### ISSUE TITLE
https://thehackernews.com/2023/11/48-malicious-npm-packages-found.html

### ISSUE THREAD

**Issue by d4op** [GhostTroops/scan4all#156]
https://thehackernews.com/2023/11/48-malicious-npm-packages-found.html

**Comment by Moostoe** [comment]
🤔

**Comment by FIXERMAN** [comment]
вот сцуко пздюк!)

**Comment by hktalent** [comment]
https://github.com/hktalent/51Pwn-Platform
Supply chain security research and verification are completed, and relevant findings have been reported
