### ISSUE TITLE
The following error appears, how can I resolve it?

### ISSUE THREAD

**Issue by sourville** [GhostTroops/scan4all#157]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x7ff6f1096e37]

goroutine 4745514109 [running]:
github.com/hktalent/scan4all/lib/util.(*CheckerTools).Check(0x0, {0xc00ebab500, 0x2, 0x2})
        D:/a/scan4all/scan4all/lib/util/checkerImp.go:80 +0x37
github.com/hktalent/scan4all/lib/util.CheckResp({0xc00f774740, 0x39}, {0xc000f14300, 0x1, 0xc014bb0188?})
        D:/a/scan4all/scan4all/lib/util/checkerImp.go:120 +0x51
github.com/hktalent/scan4all/lib/util.GetLimitReader(0xc00c46c750)
        D:/a/scan4all/scan4all/lib/util/util.go:192 +0x4f
github.com/hktalent/scan4all/lib/util.GetResponse.func1(0xc00c46c750, {0x0?, 0x0?}, {0xa?, 0xc014bb0180?})
        D:/a/scan4all/scan4all/lib/util/util.go:214 +0x1f4
github.com/hktalent/PipelineHttp.(*PipelineHttp).DoGetWithClient4SetHd(0xc0110d2000, 0x0?, {0xc014bb0180, 0x39}, {0x7ff6f260f382, 0x3}, {0x7ff6f5e204e0, 0xc007521700}, 0xc000f14710, 0xc000f14738, ...)
        D:/a/scan4all/scan4all/vendor/github.com/hktalent/PipelineHttp/PipelineHttp.go:277 +0xa6a
github.com/hktalent/scan4all/lib/util.GetResponse({0x0, 0x0}, {0x0, 0x0}, {0xc014bb0180, 0x39}, {0x7ff6f260f382, 0x3}, {0x0, 0x0}, ...)
        D:/a/scan4all/scan4all/lib/util/util.go:205 +0x285
github.com/hktalent/scan4all/lib/util.HttpRequset({0xc014bb0180, 0x39}, {0x7ff6f260f382?, 0x0?}, {0x0?, 0x882?}, 0xb0?, 0xc00b9350c8?)
        D:/a/scan4all/scan4all/lib/util/util.go:244 +0x5e
github.com/hktalent/scan4all/brute.CheckLoginPage({0xc014bb0180, 0x39}, 0xc00ac6cfa0)
        D:/a/scan4all/scan4all/brute/check_loginpage.go:27 +0x9c
github.com/hktalent/scan4all/pkg/httpx/runner.(*Runner).analyze(_, _, {_, _}, {_, _}, {_, _}, {0xc013b61920, 0x1b}, ...)
        D:/a/scan4all/scan4all/pkg/httpx/runner/runner.go:1281 +0x576e
github.com/hktalent/scan4all/pkg/httpx/runner.(*Runner).process.func1({0xc013b61920, 0x1b}, {0x7ff6f260f382, 0x3}, {0xc013b61920, 0x5})
        D:/a/scan4all/scan4all/pkg/httpx/runner/runner.go:711 +0x165
created by github.com/hktalent/scan4all/pkg/httpx/runner.(*Runner).process in goroutine 14194        D:/a/scan4all/scan4all/pkg/httpx/runner/runner.go:709 +0x73b

**Comment by hktalent** [comment]
use 2.9.0
