### ISSUE TITLE
Add macOS to the Github Action

### ISSUE THREAD

**Issue by Drjacky** [GhostTroops/scan4all#159]
I see you have old versions for macOS: https://github.com/GhostTroops/scan4all/blob/9a9e2d5b40ccb49074bbef3b7826a096102cfca8/Formula.rb#L4

Can you release the latest for macOS? or add Github Action to build for macOS as well?

**Comment by suzuki-shunsuke** [comment]
Recent Releases failed.

https://github.com/GhostTroops/scan4all/actions

<img width="858" alt="image" src="https://github.com/GhostTroops/scan4all/assets/13323303/abf95891-d497-4c2c-a161-a82cb2fd57d4">

https://github.com/GhostTroops/scan4all/actions/runs/6978505999/job/18990029445

```
Run goreleaser/goreleaser-action@v2
Downloading https://github.com/goreleaser/goreleaser/releases/download/v1.22.1/goreleaser_Darwin_all.tar.gz
Extracting GoReleaser
/usr/bin/tar xz -C /Users/runner/work/_temp/7cbb8c22-bb8d-479c-8f5d-005a7fa5ba1e -f /Users/runner/work/_temp/44aa81f3-29ee-46dc-80d5-9e58c0f6575b
GoReleaser latest installed successfully
2.8.9 tag found for commit '9a9e2d5b'
/Users/runner/hostedtoolcache/goreleaser-action/1.22.1/x64/goreleaser release -f .github/build/mac.yml --clean
  • starting release...
  • loading                                          path=.github/build/mac.yml
  • loading environment variables
    • using token from $GITHUB_TOKEN
  • getting and validating git state
    • git state                                      commit=9a9e2d5b40ccb49074bbef3b7826a096102cfca8 branch=HEAD current_tag=2.8.9 previous_tag=2.8.8 dirty=true
    • took: 2s
  ⨯ release failed after 1s                  error=git is in a dirty state
Please check in your pipeline what can be changing the following files:
 M tools/The-Hacker-Recipes

Learn more at https://goreleaser.com/errors/dirty
```

It seems the Git submodule `tools/The-Hacker-Recipes` was dirty.

```
  ⨯ release failed after 1s                  error=git is in a dirty state
Please check in your pipeline what can be changing the following files:
 M tools/The-Hacker-Recipes

Learn more at https://goreleaser.com/errors/dirty
```

https://github.com/GhostTroops/scan4all/blob/9a9e2d5b40ccb49074bbef3b7826a096102cfca8/.gitmodules#L21-L24

I'm not sure why the submodule was dirty.

**Comment by hktalent** [comment]
Thank you very much for finding and sharing these errors
Been busy recently
Have to wait some time

**Comment by hktalent** [comment]
https://github.com/GhostTroops/scan4all/releases/

**Comment by Drjacky** [comment]
> https://github.com/GhostTroops/scan4all/releases/

Could we also have aarch64? (for Apple Silicon)
