### ISSUE TITLE
mac m1 使用源码 go build 报错

### ISSUE THREAD

**Issue by niuTT** [GhostTroops/scan4all#160]
<img width="1399" alt="image" src="https://github.com/GhostTroops/scan4all/assets/41726904/fb0ac2d7-a3a9-49a6-a2a8-2086b643c1b2">

**Comment by hktalent** [comment]
Thank you very much for finding and sharing these errors
Been busy recently
Have to wait some time

**Comment by hktalent** [comment]
抱歉github上arm编译要付费，短期无法编译arm版本了
