### ISSUE TITLE
只有端口扫描结果，没有漏洞扫描

### ISSUE THREAD

**Issue by CIA-ai** [GhostTroops/scan4all#163]
运行scan4all.exe -host xx.xx.xx.xx，只有端口扫描结果，没有漏洞扫描，请问是怎么回事呢

**Comment by hktalent** [comment]
需要开启fuzz，所有的扫描都基于指纹，指纹仅仅来源httpx模块是不够的，所以需要开启目录遍历的fuzz
也就是config.json中
```
"enableFileFuzz": true,
```
