### ISSUE TITLE
[FTL] Could not run enumeration: Could not run nmap command: exit status 255

### ISSUE THREAD

**Issue by qiuluo-oss** [GhostTroops/scan4all#167]
![image](https://github.com/GhostTroops/scan4all/assets/72497146/34564250-0b4e-468d-b1fc-1374a819966d)

**Comment by hktalent** [comment]
It is recommended that you use nmap directly outside the tool, output the xml file, and then use the xml file as the parameter of scan4all
./scan4all -l nmapRssuilt.xml -v
